/* Builds the tiny native exe: release/MapleTax.exe (~1-2MB).
   Embeds the web app + WebView2 assemblies, compiles with the inbox
   .NET Framework csc.exe. No workload/SDK install needed.
   Usage: node tools/build-native.js  (or: npm run dist-native) */
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const NATIVE = path.join(ROOT, 'native');
const RELEASE = path.join(ROOT, 'release');
const WV2_VERSION = '1.0.4191.47';
const CACHE = path.join(process.env.TEMP || process.env.TMP || ROOT, 'mapletax-wv2', WV2_VERSION);

const WWW = ['index.html', 'styles.css', 'app.js', 'tax-data.js', 'cra.js', 'updater.js',
  'tables/manifest.json', 'tables/2024.json', 'tables/2025.json', 'tables/2026.json'];

const SHIM = "window.mapleTax = { isDesktop: true, " +
  "fetchText: function(u){ return chrome.webview.hostObjects.mapleTax.FetchText(u); }, " +
  "readBundled: function(p){ return chrome.webview.hostObjects.mapleTax.ReadBundled(p); } };";

async function ensureWv2() {
  const core = path.join(CACHE, 'Core.dll'), forms = path.join(CACHE, 'Forms.dll');
  const l64 = path.join(CACHE, 'Loader64.dll'), l86 = path.join(CACHE, 'Loader86.dll');
  if (fs.existsSync(core) && fs.existsSync(forms) && fs.existsSync(l64) && fs.existsSync(l86)) return { core, forms, l64, l86 };
  fs.mkdirSync(CACHE, { recursive: true });
  console.log('downloading WebView2 SDK ' + WV2_VERSION + ' (one-time cache)…');
  const url = 'https://api.nuget.org/v3-flatcontainer/microsoft.web.webview2/' + WV2_VERSION + '/microsoft.web.webview2.' + WV2_VERSION + '.nupkg';
  const r = await fetch(url);
  if (!r.ok) throw new Error('nupkg download failed: HTTP ' + r.status);
  const zip = path.join(CACHE, 'wv2.zip');
  fs.writeFileSync(zip, Buffer.from(await r.arrayBuffer()));
  const za = path.join(ROOT, 'node_modules', '7zip-bin', 'win', 'x64', '7za.exe');
  const out = path.join(CACHE, 'pkg');
  if (fs.existsSync(za)) execFileSync(za, ['x', '-y', '-bd', zip, '-o' + out], { stdio: 'ignore' });
  else execFileSync('powershell.exe', ['-NoProfile', '-Command', "Expand-Archive -LiteralPath '" + zip + "' -DestinationPath '" + out + "' -Force"]);
  fs.copyFileSync(path.join(out, 'lib', 'net462', 'Microsoft.Web.WebView2.Core.dll'), core);
  fs.copyFileSync(path.join(out, 'lib', 'net462', 'Microsoft.Web.WebView2.WinForms.dll'), forms);
  fs.copyFileSync(path.join(out, 'runtimes', 'win-x64', 'native', 'WebView2Loader.dll'), l64);
  fs.copyFileSync(path.join(out, 'runtimes', 'win-x86', 'native', 'WebView2Loader.dll'), l86);
  return { core, forms, l64, l86 };
}

function b64(file) { return fs.readFileSync(file).toString('base64'); }
function b64text(s) { return Buffer.from(s, 'utf8').toString('base64'); }

(async () => {
  const wv2 = await ensureWv2();
  const lines = [];
  lines.push('// AUTO-GENERATED by tools/build-native.js — do not edit.');
  lines.push('using System;');
  lines.push('using System.Collections.Generic;');
  lines.push('namespace MapleTax {');
  lines.push('internal static class Embedded {');
  lines.push('internal const string Shim = @"' + SHIM.replace(/"/g, '""') + '";');
  lines.push('internal static readonly byte[] Wv2Core = Convert.FromBase64String("' + b64(wv2.core) + '");');
  lines.push('internal static readonly byte[] Wv2Forms = Convert.FromBase64String("' + b64(wv2.forms) + '");');
  lines.push('internal static readonly byte[] LoaderX64 = Convert.FromBase64String("' + b64(wv2.l64) + '");');
  lines.push('internal static readonly byte[] LoaderX86 = Convert.FromBase64String("' + b64(wv2.l86) + '");');
  lines.push('private static readonly Dictionary<string, string> B64 = new Dictionary<string, string>() {');
  WWW.forEach(f => {
    const full = path.join(ROOT, ...f.split('/'));
    lines.push('{"' + f + '", "' + b64(full) + '"},');
  });
  lines.push('};');
  lines.push('private static Dictionary<string, byte[]> cache = null;');
  lines.push('private static Dictionary<string, byte[]> Cache() {');
  lines.push('if (cache == null) { cache = new Dictionary<string, byte[]>();');
  lines.push('foreach (KeyValuePair<string, string> kv in B64) cache[kv.Key] = Convert.FromBase64String(kv.Value); }');
  lines.push('return cache; }');
  lines.push('internal static int FileCount { get { return Cache().Count; } }');
  lines.push('internal static long TotalBytes { get { long n = 0; foreach (byte[] b in Cache().Values) n += b.Length; return n; } }');
  lines.push('internal static byte[] GetFile(string name) { byte[] b = GetFileOrNull(name); if (b == null) throw new System.IO.FileNotFoundException(name); return b; }');
  lines.push('internal static byte[] GetFileOrNull(string name) { byte[] b; return Cache().TryGetValue(name, out b) ? b : null; }');
  lines.push('} }');
  fs.mkdirSync(NATIVE, { recursive: true });
  fs.writeFileSync(path.join(NATIVE, 'Embedded.cs'), lines.join('\r\n'));
  console.log('generated native/Embedded.cs');

  const windir = process.env.WINDIR || 'C:\\Windows';
  const csc = path.join(windir, 'Microsoft.NET', 'Framework64', 'v4.0.30319', 'csc.exe');
  if (!fs.existsSync(csc)) throw new Error('csc.exe not found — .NET Framework 4.x required');
  fs.mkdirSync(RELEASE, { recursive: true });
  const out = path.join(RELEASE, 'MapleTax.exe');
  execFileSync(csc, ['/nologo', '/t:winexe', '/platform:anycpu', '/optimize',
    '/out:' + out,
    path.join(NATIVE, 'MapleTax.cs'), path.join(NATIVE, 'Embedded.cs'),
    '/r:System.dll', '/r:System.Drawing.dll', '/r:System.Windows.Forms.dll', '/r:System.Net.Http.dll',
    '/r:' + wv2.core, '/r:' + wv2.forms],
    { stdio: 'inherit' });
  const kb = Math.round(fs.statSync(out).size / 1024);
  console.log('built ' + out + ' (' + kb + ' KB)');
})().catch(e => { console.error('NATIVE BUILD FAILED:', e.message); process.exit(1); });
